In [2]:
from __future__ import print_function 
import torch
print(torch.__version__)

1.7.0+cpu


In [3]:
# Construct a 5x3 matrix, uninitialized:
x=torch.empty(5,3)
print(x)

tensor([[ 8.8013e-16,  4.5876e-41,  3.3359e-17],
        [ 4.5876e-41, -1.0028e+19,  4.5874e-41],
        [-1.0029e+19,  4.5874e-41, -2.3980e+18],
        [ 4.5874e-41, -2.3980e+18,  4.5874e-41],
        [-9.9764e+18,  4.5874e-41, -9.9766e+18]])


In [4]:
# Construct a randomly initialized matrix:
x=torch.rand(5,3)
print(x)

tensor([[0.1090, 0.5237, 0.3511],
        [0.2002, 0.3076, 0.2184],
        [0.1577, 0.3458, 0.9178],
        [0.2581, 0.4871, 0.5142],
        [0.5585, 0.0473, 0.4673]])


In [5]:
# Construct a matrix filled zeros and of dtype long:
x=torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# Construct a tensor directly from data:
x=torch.tensor([5.5,3])
print(x)


tensor([5.5000, 3.0000])


In [8]:
# or create a tensor based on an existing tensor.These methods will reuse the properties of the input tensor, e.g. dtype, unless new values are provided by user

x=x.new_ones(5,3, dtype=torch.double)   # new_*methods take in size 
print(x)

x=torch.randn_like(x, dtype=torch.float) # override dtype
print(x)                                 # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.7046, -0.1483,  0.0660],
        [ 1.4111,  0.3282, -0.6226],
        [ 0.6397,  0.4329, -0.4854],
        [-0.3726, -2.8136, -0.4727],
        [ 0.2640,  1.0244,  1.7295]])


# Operations

In [12]:
# Addition: syntax 1 
y=torch.rand(5,3)
print(x+y)

tensor([[ 2.2391,  0.6326,  0.4429],
        [ 1.7339,  0.4948, -0.2528],
        [ 1.3361,  0.8221, -0.0496],
        [ 0.3794, -2.2043, -0.4321],
        [ 0.3957,  1.9901,  2.4795]])


In [13]:
# Addition: syntax 2
print(torch.add(x,y))

tensor([[ 2.2391,  0.6326,  0.4429],
        [ 1.7339,  0.4948, -0.2528],
        [ 1.3361,  0.8221, -0.0496],
        [ 0.3794, -2.2043, -0.4321],
        [ 0.3957,  1.9901,  2.4795]])


In [14]:
# Addition: providing an output tensor as argument
result=torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[ 2.2391,  0.6326,  0.4429],
        [ 1.7339,  0.4948, -0.2528],
        [ 1.3361,  0.8221, -0.0496],
        [ 0.3794, -2.2043, -0.4321],
        [ 0.3957,  1.9901,  2.4795]])


In [15]:
# Addition: in-place
y.add_(x)
print(y)

tensor([[ 2.2391,  0.6326,  0.4429],
        [ 1.7339,  0.4948, -0.2528],
        [ 1.3361,  0.8221, -0.0496],
        [ 0.3794, -2.2043, -0.4321],
        [ 0.3957,  1.9901,  2.4795]])


In [18]:
print(x[:,-2::])

tensor([[-0.1483,  0.0660],
        [ 0.3282, -0.6226],
        [ 0.4329, -0.4854],
        [-2.8136, -0.4727],
        [ 1.0244,  1.7295]])


In [21]:
# Resizing: if you want to resize/reshape tensor, you can use torch.view

x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8) # the size -1 is inferred from other dimensions

print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
# If you have a one element tensor,use .item() to get the value as a python number 

x=torch.randn(1)
print(x)
print(x.item())

tensor([-1.8917])
-1.8917261362075806


# Numpy Bridge

In [23]:
# Converting a Torch Tensor to a Numpy Array
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
# Hot wht numpy array changed in value
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
# Converting Numpy Array to Torch Tensor
import numpy as np 
a=np.ones(5)
b=torch.from_numpy(a)
print(a)
print(b)
np.add(a,1,out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
